spazi=' '*25
print('%s Leonardo das low'%spazi)
print('%s Via foresta nera'%spazi)
print('%s Costa Strepitosa'%spazi)
print()
print()
print('Egregio signore')
print()
print('vorrei segnalare che mancano dei documenti')
print('per andare via')
print('penso che sono spariti a causa di un incedindio stradale di macchina')
print('ossequi')
print()
print('Leonardino Das low')
